apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demo-harbor-image
  name: demo-harbor-image
spec:
  containers:
  - image: harbor.hpe-taiwan-cic.net/jenkins/demo-pipeline:latest
    name: demo-harbor-image
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
