apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo-harbor-image
  name: demo-harbor-image
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31530
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: demo-harbor-image
  sessionAffinity: None
  type: NodePort
