apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo-harbor-image
  name: demo-harbor-image
  namespace: cicd-demo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31530
    port: 80
