apiVersion: v1
kind: Service
metadata:
  labels:
  name: jenkins-cicd-demo
  namespaces: cicd-demo
spec:
  ports:
  - port: 80
    nodePort: 31530
    protocol: TCP
    targetPort: 80
  selector:
    app: jenkins-cicd-demo
  type: NodePort
